swagger: '2.0'
info:
  description: This is an API for gyms to keep track of member activities
  version: 1.0.0
  title: Gym Membership API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:
  /scan_in:
    get:
      summary: Gets scan inforamtion
      description: Gets scan inforamtion
      operationId: app.get_scan_in
      parameters:
      - in: query
        name: startDate
        type: string
        required: true
        format: date-time
      - in: query
        name: endDate
        type: string
        required: true
        format: date-time
      responses:
        200:
          description: OK
        400:
          description: bad input parameter



  /body_info:
    get:
      summary: Gets update member inforamtion
      description: Gets update member inforamtion
      operationId: app.get_body_info
      parameters:
      - in: query
        name: startDate
        type: string
        required: true
        format: date-time
      - in: query
        name: endDate
        type: string
        required: true
        format: date-time
      responses:
        200:
          description: OK
        400:
          description: bad input parameter

definitions:
  ScanRecord:
    type: object
    required:
    - member_id
    - store_id
    - timestamp
    properties:
      member_id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      store_id:
        type: string
        example: A12345
      timestamp:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
  BodyInfoUpdate:
    type: object
    required:
    - member_id
    - store_id
    - body_info
    - timestamp
    properties:
      member_id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      store_id:
        type: string
        example: A12345
      body_info:
        $ref: '#/definitions/BodyInfo'
      timestamp:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
  BodyInfo:
    type: object
    required:
    - weight
    - body_fat
    properties:
      weight:
        type: integer
        example: 80
      body_fat:
        type: integer
        example: 10